server:
  port: 8081
spring:
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?serverTimezone=UTC
    username: root
    password: zhangbin
  redis:
    # 超时时间
    timeout: 10000ms
    # 服务器地址
    host: 192.168.184.128
    # 服务器端口
    port: 6379
    # 数据库
    database: 0
    # 密码
    password: zhangbin
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大连接阻塞等待时间,默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath:com/bin/mapper/*.xml
  type-aliases-package: com.bin.entity