server:
  port: 8989
spring:
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=UTC
    username: root
    password: zhangbin
mybatis-plus:
  mapper-locations: classpath:com/bin/mapper/*.xml
  type-aliases-package: com.bin.entity